# Generated by Django 4.0.4 on 2022-04-21 23:22

from django.db import migrations, models
import strategiesAPI.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('filePath', models.FilePathField(path=strategiesAPI.models.scripts_path, unique=True)),
            ],
        ),
    ]
