# Generated by Django 4.0.4 on 2022-05-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='credentials',
            table='Credentials',
        ),
    ]
