# Generated by Django 4.0.4 on 2022-05-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0003_alter_credentials_table_alter_strategies_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='credentials',
            table=None,
        ),
        migrations.AlterModelTable(
            name='strategies',
            table=None,
        ),
    ]
