# Generated by Django 4.0.4 on 2022-05-21 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategiesAPI', '0004_alter_credentials_table_alter_strategies_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='userName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
