# Generated by Django 4.0.4 on 2022-05-22 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategiesAPI', '0005_alter_credentials_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='id',
        ),
        migrations.AlterField(
            model_name='credentials',
            name='userName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
