# Generated by Django 4.0.4 on 2022-06-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0006_remove_credentials_id_alter_credentials_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papertrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('signal', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
            ],
        ),
    ]
