# Generated by Django 4.0.4 on 2022-06-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0007_papertrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ltp', models.FloatField()),
            ],
        ),
    ]
