# Generated by Django 4.0.4 on 2022-06-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0008_ltp'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='stop_loss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='target',
            field=models.FloatField(default=0.0),
        ),
    ]
