# Generated by Django 4.0.4 on 2022-06-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0010_papertrade_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
