# Generated by Django 4.0.4 on 2022-07-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0010_papertrade_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradedStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=100)),
            ],
        ),
    ]
