# Generated by Django 4.0.4 on 2022-07-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0011_papertrade_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradedStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='papertrade',
            old_name='time',
            new_name='endtime',
        ),
        migrations.AddField(
            model_name='papertrade',
            name='starttime',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
