# Generated by Django 4.0.4 on 2022-07-04 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0011_tradedstocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papertrade',
            name='time',
        ),
    ]
