# Generated by Django 4.0.4 on 2022-07-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0012_remove_papertrade_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='end_time',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='start_time',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
