# Generated by Django 4.0.4 on 2022-07-07 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0013_papertrade_end_time_papertrade_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
