# Generated by Django 4.0.4 on 2022-07-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0013_rename_endtime_papertrade_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrade',
            name='end_time',
            field=models.CharField(default='00:00', max_length=100, verbose_name='Trade Ended at'),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Stock Name'),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='start_time',
            field=models.CharField(default='00:00', max_length=100, verbose_name='Trade Started at'),
        ),
    ]
