# Generated by Django 4.0.4 on 2022-07-07 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0014_papertrade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='current_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='historical_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 7, 20, 21, 1, 28029)),
        ),
    ]
