# Generated by Django 4.0.4 on 2022-07-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0014_alter_papertrade_end_time_alter_papertrade_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltp',
            name='change',
            field=models.FloatField(default=0.0),
        ),
    ]
