# Generated by Django 4.0.4 on 2022-07-07 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0015_papertrade_current_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrade',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
