# Generated by Django 4.0.4 on 2022-07-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0015_ltp_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltp',
            name='change',
        ),
    ]
