# Generated by Django 4.0.4 on 2022-07-07 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0016_alter_papertrade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrade',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='end_time',
            field=models.CharField(default='00:00', max_length=100, verbose_name='Trade Ended at'),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Stock Name'),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='start_time',
            field=models.CharField(default='00:00', max_length=100, verbose_name='Trade Started at'),
        ),
    ]
