# Generated by Django 4.0.4 on 2022-07-07 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0016_remove_ltp_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
