# Generated by Django 4.0.4 on 2022-07-07 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0017_alter_papertrade_date_alter_papertrade_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrade',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
