# Generated by Django 4.0.4 on 2022-07-07 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0017_papertrade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='current_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='historical_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
