# Generated by Django 4.0.4 on 2022-07-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0018_papertrade_current_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='ltp',
            field=models.FloatField(default=0.0),
        ),
    ]
