# Generated by Django 4.0.4 on 2022-07-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0018_alter_papertrade_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papertrade',
            name='date',
        ),
    ]
