# Generated by Django 4.0.4 on 2022-07-07 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0019_remove_papertrade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
