# Generated by Django 4.0.4 on 2022-07-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0019_papertrade_ltp'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='net_charges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='net_pl',
            field=models.FloatField(default=0.0),
        ),
    ]
