# Generated by Django 4.0.4 on 2022-07-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0020_papertrade_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LTP',
        ),
        migrations.AddField(
            model_name='papertrade',
            name='ltp',
            field=models.FloatField(default=0.0, verbose_name='LTP'),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='net_charges',
            field=models.FloatField(default=0.0, verbose_name='Total Charges'),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='net_pl',
            field=models.FloatField(default=0.0, verbose_name='Net P/L'),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='current_volume',
            field=models.IntegerField(default=0, verbose_name='Current Volume'),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='historical_volume',
            field=models.IntegerField(default=0, verbose_name='Historical Volume'),
        ),
    ]
