# Generated by Django 4.0.4 on 2022-07-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0021_alter_papertrade_current_volume_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LTP',
        ),
    ]
