# Generated by Django 4.0.6 on 2022-07-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0021_delete_ltp_papertrade_ltp_papertrade_net_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategies',
            name='filePath',
            field=models.FilePathField(path='/home/algotest/Desktop/algoTrade/backend/strategiesAPI/scripts', unique=True),
        ),
    ]
