# Generated by Django 4.0.6 on 2022-07-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0022_alter_strategies_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='sl_trail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='target',
            field=models.FloatField(default=100000),
        ),
    ]
