# Generated by Django 4.0.6 on 2022-07-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategiesAPI', '0023_papertrade_sl_trail_alter_papertrade_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='Invested',
            field=models.FloatField(default=100000),
        ),
    ]
