# Generated by Django 4.0.3 on 2022-04-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aliceBlueID',
            field=models.CharField(default=1, max_length=20, unique=True),
        ),
    ]
