# Generated by Django 4.0.3 on 2022-04-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0002_alter_customuser_aliceblueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pAndL',
            field=models.FloatField(default=1),
        ),
    ]
