# Generated by Django 4.0.3 on 2022-04-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0003_customuser_pandl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pAndL',
            field=models.FloatField(default=0),
        ),
    ]
