# Generated by Django 4.0.3 on 2022-04-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0006_customuser_pandl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pAndL',
        ),
    ]
