# Generated by Django 4.0.3 on 2022-04-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0007_remove_customuser_pandl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
            ],
        ),
    ]
