# Generated by Django 4.0.3 on 2022-04-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0008_histo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Histo',
        ),
    ]
