# Generated by Django 4.0.4 on 2022-05-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isCredential',
            field=models.BooleanField(default=False),
        ),
    ]
