# Generated by Django 4.0.6 on 2022-07-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltp',
            name='ltp',
            field=models.FloatField(default=0.0),
        ),
    ]
