# Generated by Django 4.0.3 on 2022-03-31 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_aliceblue_aliceid_alter_aliceblue_aliceblueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliceblue',
            name='aliceId',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
