# Generated by Django 4.0.3 on 2022-03-31 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_aliceblue_aliceid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aliceblue',
            table='Alice Blue',
        ),
    ]
